= cfe_18

Main Data Management System (MDMS) is a tool for handling master data.

Takes advantage of relational-database standardization and MariaDB system-versioning.

Uses flyway migration strategy to ensure fault-free deployment and presents data through Swagger-ui via RESTful endpoints.

== Features

* Can be used to manage integrations
* Schema structure can be modified to accommodate user needs

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== Limitations

* Java 8

== How to [compile/use/implement]

. Setup database according to end-user needs
. Can be deployed using https://tomcat.apache.org/tomcat-9.0-doc/deployer-howto.html[tomcat]/JBoss

== How to run in a container?

Containerized deployment for CFE-18. Requires external database to use. It uses public tomcat docker image (tomcat:8-jre8-temurin-focal)

Expected files are:

`/etc/tomcat/Catalina/localhost/cfe-18/application.properties`
`/etc/tomcat/Catalina/localhost/cfe-18/log4j2.xml`

Example files for configuration are:

`docker/application.properties`
`docker/log4j2.xml`

docker/application.properties requires configuring:

* spring.datasource.url = jdbc:mariadb://127.0.0.1:3306/cfe_18
* spring.datasource.username = username
* spring.datasource.password = password
* spring.datasource.driver-class-name = org.mariadb.jdbc.Driver

(Recommended to use MariaDB as database)


.Example run command
[source,console]
----
$ docker run -ti  -v docker/application.properties:/etc/tomcat/Catalina/localhost/cfe-18/application.properties:ro -v docker/log4j2.xml:/etc/tomcat/Catalina/localhost/cfe-18/log4j2.xml:ro  -p 8080:8080 ghcr.io/teragrep/cfe_18:latest
----
where

1. application.properties and log4j2.xml are mounted accordingly.
2. 8080:8080 are for external and internal ports.
3. ghcr.io/teragrep/cfe_18:latest image from Githubs image repository


== Contributing

You can involve yourself with our project by https://github.com/teragrep/cfe_18/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once.
After submitting the CLA you can contribute to all Teragrep's repositories.
