= cfe_18

Main Data Management System (MDMS) is a tool for handling master data.

Takes advantage of relational-database standardization and MariaDB system-versioning.

Uses flyway migration strategy to ensure fault-free deployment and presents data through Swagger-ui via RESTful endpoints.

== Features

* Can be used to manage integrations
* Schema structure can be modified to accommodate user needs

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== Limitations

* Java 8

== How to [compile/use/implement]

. Setup database according to end-user needs
. Can be deployed using https://tomcat.apache.org/tomcat-9.0-doc/deployer-howto.html[tomcat]/JBoss

== How to run in a container?

****
Files are stored under `quadlets/docker` directory. They are viable for containerized deployment without quadlets.
****

Containerized deployment for CFE-18. Requires external database to use. It uses https://docs.docker.com/build/building/multi-stage/[multi-stage] to build Rocky Linux 9 as base image.

Expected files are:

`/etc/tomcat/Catalina/localhost/cfe-18/application.properties`
`/etc/tomcat/Catalina/localhost/cfe-18/log4j2.xml`

Example files for configuration are:

`/quadlets/docker/application.properties`
`/quadlets/docker/log4j2.xml`

/quadlets/docker/application.properties requires configuring:

* spring.datasource.url = jdbc:mariadb://127.0.0.1:3306/cfe_18
* spring.datasource.username = username
* spring.datasource.password = password
* spring.datasource.driver-class-name = org.mariadb.jdbc.Driver

(Recommended to use MariaDB as database)

.Example run command
[source,console]
----
$ docker run -ti  -v /quadlets/docker/application.properties:/etc/tomcat/Catalina/localhost/cfe-18/application.properties:ro -v /quadlets/docker/log4j2.xml:/etc/tomcat/Catalina/localhost/cfe-18/log4j2.xml:ro  -p 8080:8080 ghcr.io/teragrep/cfe_18:latest
----
where

1. application.properties and log4j2.xml are mounted accordingly.
2. 8080:8080 are for external and internal ports.
3. ghcr.io/teragrep/cfe_18:latest image from Githubs image repository



=== How to run container with quadlets

https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html[quadlets docs]

*****
This is the recommended deployment style for containerized deployment. Running podman containers without quadlets results them not starting independently after host reboots.
*****

==== docker directory
Files required for tomcat to deploy CFE_18. Explained on `How to run in a container?`

==== docker-entrypoint-initdb.d directory
Files required for MariaDB to initialize MariaDB with correct databases intact.
MariaDB initialization script docs : https://hub.docker.com/_/mariadb[Initializing the database contents]

==== cfe18.container
----
[Unit]
Description=CFE_18 container
Requires=cfe18mariadb.service

[Container]
Image=ghcr.io/teragrep/cfe_18:latest
Volume=/opt/teragrep/cfe_18/app:/etc/tomcat/Catalina/localhost/cfe_18:Z
PublishPort=8080:8080
# Static IP for cfe_18
IP=10.88.0.3

[Install]
# Start by default on boot
WantedBy=multi-user.target default.target
----
Keywords explained

- Requires , Needs to have mariadb service running before starting cfe18 container
- Image , Pulls image from gchr.io to be used for container deployment
- Volume , mounts contents of  `quadlets/docker` under Tomcat configuration. (application.properties and log4j2.xml)
- PublishPort , Opens internal and external port for accessing CFE_18
- IP , Declare IP in podman subnet

==== cfe18mariadb.container
----
[Unit]
Description=Database container for CFE_18

[Container]
Image=docker.io/mariadb:11.5
SecurityLabelDisable=true
# Should be stored as a secret when actually using to deploy.
Environment=MARIADB_ROOT_PASSWORD=password
# Static IP for cfe_18 to connect to
IP=10.88.0.2
# DB initialization script
Volume=/opt/teragrep/cfe_18/database/init:/docker-entrypoint-initdb.d
# Persistent Storage
Volume=/opt/teragrep/cfe_18/database/data:/var/lib/mysql

[Install]
WantedBy=multi-user.target default.target
----
Keywords explained

- Image , Pulls image from gchr.io to be used for container deployment
- SecurityLabelDisable , Turns off SELinux labeling
- Environment , Env variable which is required by MariaDB image to install MariaDB inside the container
- IP , Declare IP in podman subnet
- Volume(1) , Mounts contents of  `quadlets/docker-entrypoint-inidb.d` into the container for MariaDB to start database initialization
- Volume(2) , Creates persistent storage which is saved on host under `/opt/teragrep/cfe_18/database/data`


== Contributing

You can involve yourself with our project by https://github.com/teragrep/cfe_18/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once.
After submitting the CLA you can contribute to all Teragrep's repositories.
