////
Integration main data management for Teragrep
Copyright (C) 2025 Suomen Kanuuna Oy

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.

Additional permission under GNU Affero General Public License version 3
section 7

If you modify this Program, or any covered work, by linking or combining it
with other code, such other code is not for that reason alone subject to any
of the requirements of the GNU Affero GPL version 3 as long as this Program
is the same Program as licensed from Suomen Kanuuna Oy without any additional modifications.

Supplemented terms under GNU Affero General Public License version 3
section 7

Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
versions must be marked as "Modified version of" The Program.

Names of the licensors and authors may not be used for publicity purposes.

No rights are granted for use of trade names, trademarks, or service marks
which are in The Program if any.

Licensee must indemnify licensors and authors for any liability that these
contractual assumptions impose on licensors and authors.

To the extent this program is licensed as part of the Commercial versions of
Teragrep, the applicable Commercial License may apply to this file if you as
a licensee so wish it.
////

= File-based Host
:toc:
:toclevels: 4
:icons: font

== How?

=== Destination
[source]
----
${cfe_18_address}/host/file
----
'''

=== Request

[source,json]
----
{
  "md5": "12345678901234567890123456789012",
  "fqHost": "fqHostFromTheHost",
  "hub_fq": "fqHostForTheHub"
}
----
* `md5` is gotten from the Host configuration
* `fqHost` is gotten from the Host configuration
* `hub_fq` should be a "fqHost" from link:../hub.adoc#_request[a hub]

'''

=== Response
==== Successful request
....
HTTP Response code: 201
....
[source,json]
----
{
  "id": 123,
  "message": "New host created with cfe type"
}
----

==== Failed requests
===== Hub does not exist
If link:../hub.adoc[hubs] are not inserted before inserting Hosts, this error will be returned.
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": "Hub does not exist"
}
----

===== ID, MD5 or fqHost already exists
As all Hosts are found in a single table, there is a chance that a Host might already exist there, but not in the file-based Hosts table.
If that ID from the "global" Hosts table, MD5 or the fqHost is already found in the file-based Hosts table, that will end up in this error.
....
HTTP Response code: 400
....
[source,json]
----
{
  "message": "ID,MD5 or fqhost already exists"
}
----

===== Unexpected error
....
HTTP Response code: 500
....
[source,json]
----
{
  "id": 123,
  "message": "Unexpected error"
}
----

[#_why]
== Why?
* A Host determines where a particular Capture needs to be gathered from
** This is linked via link:../linkage.adoc["Host Group X Capture Group" link], where:
*** Let's say that a Host Group contains 3 Hosts, and a Capture Group contains 3 Captures.
*** All the 3 captures are to be found in *all* the Hosts

