////
Integration main data management for Teragrep
Copyright (C) 2025 Suomen Kanuuna Oy

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.

Additional permission under GNU Affero General Public License version 3
section 7

If you modify this Program, or any covered work, by linking or combining it
with other code, such other code is not for that reason alone subject to any
of the requirements of the GNU Affero GPL version 3 as long as this Program
is the same Program as licensed from Suomen Kanuuna Oy without any additional modifications.

Supplemented terms under GNU Affero General Public License version 3
section 7

Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
versions must be marked as "Modified version of" The Program.

Names of the licensors and authors may not be used for publicity purposes.

No rights are granted for use of trade names, trademarks, or service marks
which are in The Program if any.

Licensee must indemnify licensors and authors for any liability that these
contractual assumptions impose on licensors and authors.

To the extent this program is licensed as part of the Commercial versions of
Teragrep, the applicable Commercial License may apply to this file if you as
a licensee so wish it.
////

= File processing instructions for file-based Capture Definitions
:toc:
:toclevels: 4
:icons: font

== How?

=== Destination

[source]
----
PUT ${cfe_18_address}/file/capture/meta/rule
----
'''

=== Request

[source,json]
----
{
  "inputtype": "inputType1",
  "inputvalue": "123456",
  "ruleset": "RuleNumber1",
  "name": "CaptureMeta1",
  "template": "template1"
}
----
'''

=== Response
==== Successful request
....
HTTP Response code: 201
....
[source,json]
----
{
  "id": null,
  "message": "New processing type created with the name = CaptureMeta1"
}
----

==== Failed requests

===== Duplicate record
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 0,
  "message": "FileCaptureMeta name already exists with different values"
}
----

===== Null value
If one of the values in the JSON request is `null`
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 0,
  "message": "NO NULLS ALLOWED"
}
----

===== Unknown error
If something else goes wrong
....
HTTP Response code: 500
....
[source,json]
----
{
  "id": 0,
  "message": "Unexpected error"
}
----

== Why?
* fileCaptureMeta provides metadata for link:fileCaptureDefinition.adoc[file-based captures], how to process them
* Needs to be inserted before the Captures, so that the ID for the CaptureMeta can be linked to a link:fileCaptureDefinition.adoc[Capture]
