////
Integration main data management for Teragrep
Copyright (C) 2025 Suomen Kanuuna Oy

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.

Additional permission under GNU Affero General Public License version 3
section 7

If you modify this Program, or any covered work, by linking or combining it
with other code, such other code is not for that reason alone subject to any
of the requirements of the GNU Affero GPL version 3 as long as this Program
is the same Program as licensed from Suomen Kanuuna Oy without any additional modifications.

Supplemented terms under GNU Affero General Public License version 3
section 7

Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
versions must be marked as "Modified version of" The Program.

Names of the licensors and authors may not be used for publicity purposes.

No rights are granted for use of trade names, trademarks, or service marks
which are in The Program if any.

Licensee must indemnify licensors and authors for any liability that these
contractual assumptions impose on licensors and authors.

To the extent this program is licensed as part of the Commercial versions of
Teragrep, the applicable Commercial License may apply to this file if you as
a licensee so wish it.
////

= Storage Capture
:toc:
:toclevels: 4

== How?

=== Destination

[source]
----
PUT ${cfe_18_address}/storage/capture
----
'''

=== Request

[source,json]
----
{
  "capture_id": 123,
  "storage_id": 123
}
----

* `capture_id` should be an ID from the response of an added capture (link:relpCaptureDefinition.adoc[relp-based] or link:fileCaptureDefinition.adoc[file-based])
* `storage_id` should be the response ID from link:storage.adoc[Storage]

'''
=== Response
==== Successful request
....
HTTP Response code: 201
....
[source,json]
----
{
  "id": 123,
  "message": "New flow storage created"
}
----

==== Failed requests

===== Capture does not exist
A capture does not exist with the id in the request
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": "Capture does not exist with given ID"
}
----
How to fix: add a capture (link:relpCaptureDefinition.adoc[relp-based] or link:fileCaptureDefinition.adoc[file-based])

===== Flow Storage does not exist
A Storage does not exist with the id in the request
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": "Storage does not exist"
}
----
How to fix: add a link:storageFlow.adoc[flow Storage]

== Why?
* Links a link:storage.adoc[storage] to a capture (link:relpCaptureDefinition.adoc[relp-based] or link:fileCaptureDefinition.adoc[file-based])
* A capture can have multiple different Storages, but not many of the same type



