////
Integration main data management for Teragrep
Copyright (C) 2025 Suomen Kanuuna Oy

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.

Additional permission under GNU Affero General Public License version 3
section 7

If you modify this Program, or any covered work, by linking or combining it
with other code, such other code is not for that reason alone subject to any
of the requirements of the GNU Affero GPL version 3 as long as this Program
is the same Program as licensed from Suomen Kanuuna Oy without any additional modifications.

Supplemented terms under GNU Affero General Public License version 3
section 7

Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
versions must be marked as "Modified version of" The Program.

Names of the licensors and authors may not be used for publicity purposes.

No rights are granted for use of trade names, trademarks, or service marks
which are in The Program if any.

Licensee must indemnify licensors and authors for any liability that these
contractual assumptions impose on licensors and authors.

To the extent this program is licensed as part of the Commercial versions of
Teragrep, the applicable Commercial License may apply to this file if you as
a licensee so wish it.
////

= Calculating the tag

The tag is calculated from a Capture's tag_path using MD5 hashing.

Using an imaginary tag_path of:

[source, bash]
----
/opt/teragrep/capture-example-01/log_file.log
----

The expected MD5 hash of that string is:
`79822d06c9af7e23f33fb4488c55760c`.

Only the first 8 characters matter for the tag, so now we're left with: `79822d06`.

After this, the string after the last instance of the character `/` is separated, in this example this would be `log_file.log`.

* If the substring is *shorter or equal* to 23 characters, it is appended to the shortened MD5 hash using a dash:
+
[source,bash]
----
79822d06-log_file.log
----

* If the substring is longer than that, for example `log_file_that_is_super_long.log` (31 characters long), only the first 23 characters are used for appending:
+
[source,bash]
----
79822d06-log_file_that_is_super_
----