////
Integration main data management for Teragrep
Copyright (C) 2025 Suomen Kanuuna Oy

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.

Additional permission under GNU Affero General Public License version 3
section 7

If you modify this Program, or any covered work, by linking or combining it
with other code, such other code is not for that reason alone subject to any
of the requirements of the GNU Affero GPL version 3 as long as this Program
is the same Program as licensed from Suomen Kanuuna Oy without any additional modifications.

Supplemented terms under GNU Affero General Public License version 3
section 7

Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
versions must be marked as "Modified version of" The Program.

Names of the licensors and authors may not be used for publicity purposes.

No rights are granted for use of trade names, trademarks, or service marks
which are in The Program if any.

Licensee must indemnify licensors and authors for any liability that these
contractual assumptions impose on licensors and authors.

To the extent this program is licensed as part of the Commercial versions of
Teragrep, the applicable Commercial License may apply to this file if you as
a licensee so wish it.
////

= Linkage
:toc:
:toclevels: 4
:icons: font

== How?

=== Destination

[source]
----
${cfe_18_address}/capture/groups/linkage
----
'''

[#_request]
=== Request

[source,json]
----
{
  "host_group_id": 123,
  "capture_group_id": 123
}
----
* `host_group_id` is gotten from the response of link:host/hostGroup.adoc[Host Group]
* `capture_group_id` is gotten from the response of link:capture/captureGroup.adoc[Capture Group]

'''

=== Response
==== Successful request
....
HTTP Response code: 201
....
[source,json]
----
{
  "id": 123,
  "message": "New linkage created for groups = CaptureGroup1 and HostGroup1"
}
----
NOTE: The response returns the *names* of the Groups that are linked

==== Failed requests
===== Type mismatch
Capture and Host Groups are not of the same type (RELP or file)
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": " type mismatch between host group and capture group"
}
----

===== Host Group does not exist
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": " HOST group does not exist"
}
----

===== Capture Group does not exist
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": " CAPTURE group does not exist"
}
----

== Why?

* Provides a way to link Host Groups and Capture Groups
* This determines where a particular Capture needs to be gathered from
* See link:host/hostFile.adoc#_why[hostFile reasoning] for exact reason