////
Integration main data management for Teragrep
Copyright (C) 2025 Suomen Kanuuna Oy

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.

Additional permission under GNU Affero General Public License version 3
section 7

If you modify this Program, or any covered work, by linking or combining it
with other code, such other code is not for that reason alone subject to any
of the requirements of the GNU Affero GPL version 3 as long as this Program
is the same Program as licensed from Suomen Kanuuna Oy without any additional modifications.

Supplemented terms under GNU Affero General Public License version 3
section 7

Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
versions must be marked as "Modified version of" The Program.

Names of the licensors and authors may not be used for publicity purposes.

No rights are granted for use of trade names, trademarks, or service marks
which are in The Program if any.

Licensee must indemnify licensors and authors for any liability that these
contractual assumptions impose on licensors and authors.

To the extent this program is licensed as part of the Commercial versions of
Teragrep, the applicable Commercial License may apply to this file if you as
a licensee so wish it.
////

= Flow
:toc:
:toclevels: 4

== How?

=== Destination

[source]
----
PUT ${cfe_18_address}/sink/details
----
'''

=== Request

[source,json]
----
{
  "flow": "flowName",
  "ip_address": "127.0.0.1",
  "port": "12345",
  "protocol": "https"
}
----
'''

=== Response
==== Successful request
....
HTTP Response code: 201
....
[source,json]
----
{
  "id": 123,
  "message": "New sink created"
}
----

==== Failed requests
===== Flow and protocol combination duplicate
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": "Flow and protocol combination already exists"
}
----

===== Port length is over 5 characters long
....
HTTP Response code: 400
....
[source,json]
----
{
  "id": 123,
  "message": "Port length exceeded"
}
----

===== Unknown error
If something else goes wrong
....
HTTP Response code: 500
....
[source,json]
----
{
  "id": 0,
  "message": "Unexpected error"
}
----

== Why?
* Sinks are used to indicate the first forwarding point of the Capture
** Protocol refers to Application Layer protocol (L7 OSI model), which is being used to forward Capture
* These are required before inserting a Capture, since it needs to be linked to a Capture using both:
** Flow name
** Protocol name
* That combination is why duplicate Flow and Protocol combinations are not allowed

